### ISSUE TITLE
Make expiration time configurable for jwt

### ISSUE THREAD

**Issue by patrickwilmes** [patrickwilmes/goauth#4]
Currently, in `common.token.go` the expiration time is set to 24 hours starting now.
A user might want to adapt the expiration time, to something shorter or even longer,
and therefor, we should make the value configurable. This means:

The configuration contains a new property:
```yaml
# config.yaml
security:
    jwt:
        expirationOffsetMins: 20
```

The implementation changes to:
```go
time.Now().Add(time.Minute * common.GetInValue(jwtExpirationOffsetInMins).Unix()
```
